---
## This playbook disables password based logins and enables only key based auth.

# Apply common configuration to all hosts
- name: Secure SSH login. (Passwordless login)
  become: yes
  hosts: all
  vars_files:
  - group_vars/all

  roles:
    - secure-ssh
