---
## This playbook disables password based logins and enables only key based auth.

# Apply common configuration to all hosts
- name: Secure SSH login. (Passwordless login)
  gather_facts: no
  become: yes
  hosts: all-servers
  vars_files:
  - group_vars/all
  - group_vars/secrets

  roles:
    - secure-ssh
